services:
  # A Web Service for your Node.js API
  - type: web
    name: roblox-api-backend
    runtime: node
    branch: main
    buildCommand: "npm install"
    # Use the npm start script from package.json
    startCommand: "npm start"
    healthCheckPath: "/"

  # A Static Site for your HTML/JS Frontend
  - type: static
    name: roblox-frontend
    branch: main
    staticPublishPath: ./public
    routes:
      - type: rewrite
        source: /gamepasses/:username
        destination: https://roblox-api-backend.onrender.com/gamepasses/:username
      - type: rewrite
        source: /games/:username
        destination: https://roblox-api-backend.onrender.com/games/:username
